# For more info on HTTP files go to https://aka.ms/vs/httpfile

@WebApplication1_HostAddress = https://localhost:44303

GET {WebApplication1_HostAddress}}/weatherforecast/
Accept: application/json

###
